Add Use Cases and NFRs to DeveloperGuide.md
AY2223S1-CS2103T-W13-4/tp pull request #16
Opened 2022-09-30 09:52 UTC by ling-ui

### Changes

- Added all the use cases for features set to be implemented in v1.2 to DeveloperGuide.md 
- Added some NFRs based on our current features

While reviewing, check for:

- Grammar errors and punctuation errors.
- Whether the numbering and labels are correct
- Any other formatting errors.

2022-09-30 11:46 UTC, Devanshshah1309 requested changes

2022-09-30 11:46 UTC, Devanshshah1309 commented on docs/DeveloperGuide.md
> +**Use case: Add a member to a team**
Do we have to number the use cases (e.g. use case 1, use case 2, etc.)

2022-09-30 11:46 UTC, Devanshshah1309 commented on docs/DeveloperGuide.md
> +Preconditions: The current working team is set to the team that the member should be deleted from.
```suggestion
Precondition: The current working team is set to the team that the member should be deleted from.
```

2022-09-30 11:46 UTC, Devanshshah1309 commented on docs/DeveloperGuide.md
> +Preconditions: The current working team is set to the team that the task should be deleted from.
```suggestion
Precondition: The current working team is set to the team that the task should be deleted from.
```

2022-09-30 11:46 UTC, Devanshshah1309 commented on docs/DeveloperGuide.md
> +Preconditions: The current working team is set to the team that the member should be deleted from.
```suggestion
Precondition: The current working team is set to the team that the member should be deleted from.
```

2022-09-30 11:46 UTC, Devanshshah1309 commented on docs/DeveloperGuide.md
> +Preconditions: The current working team is set to the team that has the existing task.
Ditto on changing all `Preconditions` to `Precondition`

2022-09-30 11:46 UTC, Devanshshah1309 commented on docs/DeveloperGuide.md
> +4. Does not require internet connection.
Do we require it for our `help` functionality?

2022-10-01 00:37 UTC, ling-ui commented on docs/DeveloperGuide.md
> +4. Does not require internet connection.
Possible, I will remove this NFR for now

2022-10-01 08:53 UTC, Devanshshah1309 approved these changes
LGTM

2022-10-01 08:53 UTC, merged