Draft: Add Tasks functionality
AY2223S1-CS2103T-W13-4/tp pull request #23
Opened 2022-10-03 15:55 UTC by Devanshshah1309

To be updated once PR is complete.

Fixes #22

2022-10-08 18:14 UTC, changjy44 requested changes
Do update the relevant parts that needs to be changed and self merge when done, thanks.

2022-10-08 18:14 UTC, changjy44 commented on src/main/java/seedu/address/logic/commands/ListTasksCommand.java
> + */
Duplicate description in ListTaskCommand from AddTaskCommand, do update!

2022-10-08 18:14 UTC, changjy44 commented on src/main/java/seedu/address/logic/commands/ListTasksCommand.java
> +    }
Unnecessary javadocs for constructor, might want to shift it up.

2022-10-08 18:14 UTC, changjy44 commented on src/main/java/seedu/address/model/AddressBook.java
> +    private final TaskList taskList;
Not exactly clear why AddressBook needs a taskList reference, should taskList be only encapsulated inside Teams?

2022-10-08 18:14 UTC, changjy44 commented on src/main/java/seedu/address/model/AddressBook.java
> +
Javadocs description does not match the method, do update again.

2022-10-08 18:14 UTC, changjy44 commented on src/main/java/seedu/address/model/team/TaskList.java
> +     */
Javadocs method description does not match, do update!

2022-10-09 01:05 UTC, Devanshshah1309 commented
> Do update the relevant parts that needs to be changed and self merge when done, thanks. EDIT: Do configure your TaskListPanel to appear in the UI as well, I will build the Teams UI around your TaskListPanel.

Not sure if it is right to have the `TaskListPanel` without the `TeamsListPanel` though

2022-10-09 01:10 UTC, Devanshshah1309 commented
Do you think we can implement all the UI changes once both the `Team` and `Task` implementations are stabilised? We might need to discuss with the team on how we want the UI to look like for different commands (e.g. Do we always want tasks to be shown on the right panel? Or, do we want the tasks to replace the `TeamListPanel` when `list_tasks` is run?). I think it might be better to get the logic + implementation of designs done before we move on to fixing the UI. What do you think? (hopefully if the `Team` and `Tasks` is settled by tuesday, we can still implement the UI by Friday, in time for v1.2)?

2022-10-09 03:37 UTC, ling-ui commented
> Do you think we can implement all the UI changes once both the `Team` and `Task` implementations are stabilised? We might need to discuss with the team on how we want the UI to look like for different commands (e.g. Do we always want tasks to be shown on the right panel? Or, do we want the tasks to replace the `TeamListPanel` when `list_tasks` is run?). I think it might be better to get the logic + implementation of designs done before we move on to fixing the UI. What does everyone think? @changjy44 @mjgui @marcuspang @ling-ui (hopefully if the `Team` and `Tasks` is settled by tuesday, we can still implement the UI by Friday, in time for v1.2)?

I suppose we can talk about the UI during our next meeting, perhaps we focus on getting the core features up first.

2022-10-09 03:56 UTC, changjy44 approved these changes
Looks good to merge

2022-10-09 03:57 UTC, merged

2022-10-20 09:13 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/ListTasksCommand.java
> +    public static final String MESSAGE_ADD_TASK_SUCCESS = "Tasks: \n%1$s";
This should be `MESSAGE_LIST_TASK` right?