Modifying tasks
AY2223S1-CS2103T-W13-4/tp pull request #93
Opened 2022-10-23 08:20 UTC by ling-ui

Work in progress

2022-10-25 07:20 UTC, mjgui requested changes

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/AddTaskCommand.java
> +        }
Currently this has some weird behaviour if you give a list of assignees and one of them is invalid - all the valid ones from before will be assigned, but all after the invalid one won't (since the Exception is thrown)

Maybe you can consider using streams? (assuming `assignees` is also a list) maybe something like
```java
List<Person> assigneePersonList = memberList.stream()
        .filter(member -> assignees.contains(member.name))
        .collect(Collectors.toList());
```

then check that the length of `assignees` is the same as `assigneePersonList`, before looping through and assigning (this time without checking, since it's already been checked).

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/EditTaskCommand.java
> +    public static final String MESSAGE_DUPLICATE_TASK = "This task already exists.";
```suggestion
    public static final String MESSAGE_DUPLICATE_TASK = "A task with the same name already exists.";
```

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/EditTaskCommand.java
> +            }
Why are you using `getDeadlineStorage` here? Maybe we can expose a `getDeadline()` directly?

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/EditTaskCommand.java
> +            }
if you do make this change you can replace the whole if/else with a `.orElse`

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/EditTaskCommand.java
> +        }
Same as above

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
> +                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
btw we should probably refactor this datetime formatter string into a string constant in some class

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/model/ModelManager.java
>      @Override
```suggestion
    }

    @Override
```

2022-10-25 07:20 UTC, mjgui commented on src/main/java/seedu/address/model/ModelManager.java
>      @Override
?

2022-10-26 23:24 UTC, ling-ui commented on src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
> +        options.addOption(FLAG_ASSIGNEE_STR, FLAG_ASSIGNEE_STR_LONG, true, "Assignees of task");
I think add person has name of person as a flag also? Left it as it is for consistency for now

2022-10-27 05:49 UTC, mjgui requested changes
On a sep note, I feel like we should be using index not name to assign things here

2022-10-27 05:49 UTC, mjgui commented on docs/UserGuide.md
> +### Add task to team : `addtask`
```suggestion
### Add task to team : `add task`
```

2022-10-27 05:49 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/AddTaskCommand.java
> +            + "-" + FLAG_ASSIGNEE_STR + " \"Bernice Yu\" ";
the flags should already have dashes attached to them

2022-10-27 05:49 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/EditTaskCommand.java
> +                    + " \"Review PR\" " + "-" + FLAG_DEADLINE_STR + " \"2023-12-12 23:59\" ";
same as above, dashes should be included

also, for readability, try put one flag on one line?

2022-10-27 05:49 UTC, mjgui commented on src/main/java/seedu/address/logic/commands/EditTaskCommand.java
> +    /**
```suggestion
    }

    /**
```

2022-10-27 05:49 UTC, mjgui commented on src/main/java/seedu/address/model/team/Team.java
>      /**
```suggestion
    }

    /**
```

2022-10-27 12:57 UTC, mjgui approved these changes

2022-10-27 13:12 UTC, merged