Disallow selecting of tasks and teams
AY2223S1-CS2103T-W13-4/tp pull request #95
Opened 2022-10-24 08:00 UTC by Devanshshah1309

### Changes
1. Disallow selecting teams and tasks through the UI (no change in color)
2. Add links to team description.
3. Add deadline + assignee + status of task to UI
4. Change font (not sure when it reverted back to using the initial one)

2022-10-25 06:39 UTC, mjgui requested changes
Code looks good!

If possible can we add the following changes?
1. Display the URL also for the link?
2. Also, can we display some message like `URL "https://..." is copied to clipboard!` inside the output box when you click on a link? Now it's not clear what clicking on a link is supposed to do
3. Dark/Light mode
4. Help link theming

2022-10-25 06:39 UTC, mjgui commented on src/main/resources/view/LightTheme.css
> +    -fx-font-family: "Courier New", Helvetica, Arial, sans-serif;
this should me `monospace` if you want a fallback
```suggestion
    -fx-font-family: "Courier New", monospace;
```
probably the same for the other font things

2022-10-26 01:10 UTC, Devanshshah1309 commented on docs/UserGuide.md
> +the team does not exist
```suggestion
Sets the application to an existing team, i.e., changes the current "working" team to another. Will throw an error if the team does not exist
```

2022-10-26 01:10 UTC, Devanshshah1309 commented on docs/UserGuide.md
> +team.
```suggestion
Add a new team member to the user’s currently selected team. Will throw an error if the member already exists in the team.
```

2022-10-26 01:10 UTC, Devanshshah1309 commented on docs/UserGuide.md
> +YYYY-MM-DD HH:MM format.
```suggestion
Set a deadline for an existing task. Will display an error message if task is not found in the user’s team. If a deadline has been set for the task before, a new deadline will be set if command is run again. The deadline must be specified in YYYY-MM-DD HH:MM format.
```

2022-10-26 01:10 UTC, Devanshshah1309 commented on docs/UserGuide.md
> +  11.59pm.
```suggestion
* `set_deadline 1 2023-12-25 23:59` will set the deadline for the first task on the task list as 25 December 2023 11.59pm.
```

2022-10-26 01:10 UTC, Devanshshah1309 commented on docs/UserGuide.md
> +the user’s team, i.e., when the index exceeds the number of tasks.
```suggestion
Delete an existing task from the team given the task's index. Will display an error message if the task is not found in the user’s team, i.e., when the index exceeds the number of tasks.
```

2022-10-26 01:10 UTC, Devanshshah1309 commented on docs/UserGuide.md
> +remaining tasks.
```suggestion
View all the tasks currently in the user’s team in the form of a list. List can also be filtered based on complete or remaining tasks.
```

2022-10-26 03:33 UTC, marcuspang commented on src/main/java/seedu/address/model/team/Team.java
> +    public static final String VALIDATION_REGEX = "[^\\s].*";
If we don’t use alphanumeric strings, we may run into the case where they are trying to escape the string, for e.g. `\` and `”` where they may not want to include it

2022-10-26 03:35 UTC, marcuspang commented on src/main/java/seedu/address/ui/MainWindow.java
> +        primaryStage.getScene().getStylesheets().addAll(newStyleSheets);
Might be a cause of concern w.r.t. to Law of Demeter here

2022-10-26 04:12 UTC, Devanshshah1309 commented on src/main/java/seedu/address/model/team/Team.java
> +    public static final String VALIDATION_REGEX = "[^\\s].*";
Hmm okay i'm fine with having alphanumeric strings but spaces should definitely be allowed.. what do you think?

2022-10-26 04:12 UTC, Devanshshah1309 commented on src/main/java/seedu/address/ui/MainWindow.java
> +        primaryStage.getScene().getStylesheets().addAll(newStyleSheets);
Yeah it's pretty hacky but I don't think there's a better way to do this.

2022-10-26 18:02 UTC, marcuspang requested changes
Everything looks good, except some minor nits. 

For the fonts, I feel that the headings can remain as monospace bolded. However, for description-type fields, they should not be monospace as they are not bolded. Making them monospace decreases the readability especially for dark backgrounds.

2022-10-27 01:13 UTC, marcuspang approved these changes
LGTM

2022-10-27 01:15 UTC, merged